[package]
name = "terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
github = { path = "../github" }
anyhow = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
chrono-humanize = { workspace = true }
testresult = { workspace = true }
futures-util = { workspace = true }
octocrab = "0.48.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
inventory = "0.3.21"
dirs-next = "2.0.0"
tempfile = "3.12.0"
clap = { version = "4.5.18", features = ["derive"] }
textwrap = "0.16.1"
arc-swap = { version = "1.7.1", features = ["serde"] }
futures-timer = "3.0.3"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
tui-scrollview = "0.5.3"
tui-markdown = "0.3.6"
